### PR TITLE
Reviewing first few changesets by new mappers

### PR DESCRIPTION
**Pull request by bkowshik**
Add reason, `Hello, welcome to OSM!` to the first `5` changesets of a new mapper on OSM.

---

cc: @manoharuss

### CODE REVIEW

**Comment by iandees** [comment]
Why not use "new mapper" or similar as a reason instead of "Hello, welcome to OSM!"? Are these reasons seen by the users themselves?

**Comment by bkowshik** [comment]
> Why not use "new mapper" or similar as a reason instead of "Hello, welcome to OSM!"?

:wave: @iandees, `New mapper` reads great.

> Are these reasons seen by the users themselves?

Yes, once deployed this will be visible here: http://osmcha.mapbox.com/

osmcha-reason

**Comment by iandees** [comment]
Cool! I meant to ask if the "reason" text would get sent to the user as a changeset comment or anything. Sounds like it's just an internal osmcha thing.

**Comment by bkowshik** [comment]
> Cool! I meant to ask if the "reason" text would get sent to the user as a changeset comment or anything. Sounds like it's just an internal osmcha thing.

The reason text is not sent to the user. On osmcha, changeset will be a tagged with **New mapper**.

**Comment by bkowshik** [comment]
Per voice with @batpad going upstream. Changing base for the PR to [`willemarcel/osmcha`](https://github.com/willemarcel/osmcha)

**Comment by bkowshik** [comment]
@willemarcel would love to hear next actions from you to get this merged to `willemarcel/osmcha`.

**Comment by manoharuss** [comment]
@iandees Leaving this here for reference. https://github.com/willemarcel/osmcha-django/issues/67#issue-215353976

It is currently assumed that data breakages are likely to come from new users than old experienced users. There has been agreement from osm community members that they indeed spend time validating new users changesets, find issues to give feedback on/fix. http://resultmaps.neis-one.org/newestosm already shows these but OSMCha lacks this feature. This would be good addition on OSMCha to use in combination with other filters. Ex: bbox filter. Then we can do certain specific filters like, how many new user changesets have come into New York since yesterday or last month.

**Comment by bkowshik** [comment]
Did a separate PR to upstream `willemarcel/osmcha` here: https://github.com/willemarcel/osmcha/pull/16

No next actions here. Closing.

**Pull request closed without merging**
